# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: ayres_de_canning_deveopment
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: ayres_de_canning_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ayres_de_canning_production
  pool: 5
  timeout: 5000